/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecommerce;

import org.junit.Test;

import ecommerce.domain.Product;
import ecommerce.application.BasketService;
import ecommerce.application.BasketServiceOptim;
import ecommerce.infra.BasketRepositoryInMemory;

import static org.junit.Assert.*;

public class BasketServiceTest {
    @Test public void testECommerce() {
        //BasketService applicationLayer = new BasketService(new BasketRepositoryInMemory());
        BasketServiceOptim applicationLayer = new BasketServiceOptim(new BasketRepositoryInMemory());
        int basketId = applicationLayer.createBasket();
        applicationLayer.addProductToBasket(basketId, new Product(1,"super TV",100), 1);
        System.out.println("ok");
        assertEquals("should have one product in basket", applicationLayer.getProductsInBasket(basketId).size(), 1);
    }
}
